import type { Metadata } from "next";
import "./globals.css";
import { ReactQueryProvider } from "@/providers/QueryProvider";

export const metadata: Metadata = {
  title: "Strawberry Front",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <ReactQueryProvider>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
